version: "3.8"

services:
  backend:
    container_name: myclassroom_backend
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      DEV_DB_HOST: db
      DEV_DB_PASS: password
      TEST_DB_HOST: db
      TEST_DB_PASS: password
    entrypoint: ["./entrypoint.sh"]
    ports:
      - "3001:3001"
    expose:
      - "3001"

  db:
    image: mysql:latest
    container_name: myclassroom_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
